/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rustyrazorblade.temporaldemo

import io.temporal.client.WorkflowClient
import io.temporal.client.WorkflowClientOptions
import io.temporal.client.WorkflowOptions
import io.temporal.client.WorkflowStub
import io.temporal.common.converter.CodecDataConverter
import io.temporal.common.converter.DefaultDataConverter

import io.temporal.serviceclient.WorkflowServiceStubs
import java.util.concurrent.TimeUnit

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    // Create an instance that connects to a Temporal Service running on the local
    // machine, using the default port (7233)
    // This doesn't connect yet, we need the options as well.
    val service = WorkflowServiceStubs.newLocalServiceStubs()

    // Initialize the client options.
    val clientOptions = WorkflowClientOptions.newBuilder()
        .setNamespace("default")
        .setDataConverter(CodecDataConverter(DefaultDataConverter.newDefaultInstance(), listOf(SampleCodec())))
        .build()

    // Create the actual client instance, but it connects lazily.
    val client = WorkflowClient.newInstance(service, clientOptions)

    // The workflowId is a uniqueness constraint.
    val workflowOptions = WorkflowOptions.newBuilder()
        .setTaskQueue(Shared.DEMO_TASK_QUEUE)
        .setWorkflowId("monkey2").build()


    val line = args.getOrElse(0) {
        "DEFAULT"
    }

    println("Starting with $line")

    // Create a workflow.  This is not reusable.
    val workflow = client.newWorkflowStub(TestWorkflow::class.java, workflowOptions)

    // The data object we're going to use in our workflow.
    // Best practice is we use an object because
    val data = WorkflowDataImpl(line)

    val instance = WorkflowClient.start(workflow::starCoolWorkflow, data)
    println("instance: ${instance.workflowId}")

    val untyped = WorkflowStub.fromTyped(workflow)

    for(i in 0..10) {
        try {
            val result = untyped.getResult(1, TimeUnit.SECONDS, Int::class.java)
            println("RESULT? $result")
            break
        } catch (e: Exception) {
            println("OH NO MY SILLY GOOSE $e")
        }
    }
    println("Done")


    // the workflow is going to create a bunch of activities, and it will take at least a minute to run
    // so we're going to create it then monitor it
}
